dependencies:
- name: book-ui
  version: 0.0.1
  repository:  https://artifactory-tools.sandbox-ocp43-one-621532-a39cdf59c11fe9ef74002319618f3999-0000.eu-gb.containers.appdomain.cloud/artifactory/generic-local/sandbox-ocp43-tcs/
